#!/bin/bash -e

SDDM_KDE_SETTINGS="/etc/sddm.conf.d/kde_settings.conf"
 

#deactivate ExposeBlue theme
if [ -f "${SDDM_KDE_SETTINGS}" ]; then
        if grep -q "^[#]*[[:space:]]*Current=" "${SDDM_KDE_SETTINGS}"; then
                sed -i "s/^[#]*[[:space:]]*Current=.*/Current=breeze/g" "${SDDM_KDE_SETTINGS}"
        fi
fi
